= About VPC Firewall Rules

Your VPC needs its own firewall rules to allow specific IP ranges and ports from reaching your workers.

[CAUTION]
--
A Firewall Rule checks inbound connections only to your workers. Not to the VPC or your dedicated load balancer.
--

All traffic to your VPC is blocked, unless it's allowed in a firewall rule.
When creating a VPC, 4 firewall rules are created by default:

* 2 rules to allow inbound connections from your local VPC from ports `8091` and `8092`:
+
[source,json,linenums]
----
{
  "CIDR Block": "10.111.0.0/24", // (Local VPC)
  "Protocol": "TCP",
  "From port": 8092,
},

{
  "CIDR Block": "10.111.0.0/24", // (Local VPC)
  "Protocol": "TCP",
  "From port": 8091,
},
----
+
These firewall rules allow traffic from the VPC to reach your workers through ports *8091* and *8092* (these are the only ports used by your link:/runtime-manager/cloudhub-dedicated-load-balancer[*CloudHub dedicated load balancer*] to proxy all external communications to your workers through).

[TIP]
The `10.111.0.0/24` is an example of a firewall rule whose private address space was set to `10.111.0.0` and sized to have 256 IP addresses. +
These default firewall rules will show the CIDR block that you set for your VPC.

* 2 rules to allow inbound connections from anywhere through ports `8081` and `8082`:
+
[source,json,linenums]
----
{
  "CIDR Block": "0.0.0.0/0", // (Anywhere)
  "Protocol": "TCP",
  "From port": 8082,
},

{
  "CIDR Block": "0.0.0.0/0", // (Anywhere)
  "Protocol": "TCP",
  "From port": 8081,
}
----
+
These rules allow traffic from any host to reach your workers through ports 8081 and 8082 (these ports are used by *CloudHub's default load balancer* to proxy external requests to your workers).

[TIP]
--
If you don't want your internal workers to be reached by the default load balancer, follow our networking guide to link:/runtime-manager/cloudhub-networking-guide#avoiding-public-discoverability-for-applications-on-cloudhub[avoid public discoverability for applications on CloudHub].
--

You can set these rules using the Anypoint Platform CLI's link:/runtime-manager/anypoint-platform-cli#cloudhub-vpc-firewall-rules-add[firewall rule creation command] or use link:/runtime-manager/vpc-create-using-runtime-manager-workflow[the UI].
